//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P1_Aaron_Quintanal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Falta
    {
        public int FaltaId { get; set; }
        public System.DateTime Dia { get; set; }
        public int Hora { get; set; }
        public string Grupo { get; set; }
        public string Observaciones { get; set; }
        public int ProfeFalta { get; set; }
        public Nullable<int> ProfeSusti { get; set; }
    }
}
