//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoocan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animale
    {
        public int AnimalId { get; set; }
        public int RefugioId { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Nacimiento { get; set; }
        public System.DateTime Entrada { get; set; }
        public string Especie { get; set; }
        public string Raza { get; set; }
        public float Peso { get; set; }
        public int EspacioMin { get; set; }
    }
}
