//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoocan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refugio
    {
        public int RefugioId { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Especie { get; set; }
        public string Telefono { get; set; }
        public int MaxAnimales { get; set; }
    }
}
