//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoocanV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int AnimalId { get; set; }
        public int RefugioId { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Nacimiento { get; set; }
        public System.DateTime Entrada { get; set; }
        public string Especie { get; set; }
        public string Raza { get; set; }
        public float Peso { get; set; }
        public int EspacioMin { get; set; }
    }
}
